# Generated by Django 4.2.5 on 2023-09-15 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('desc', models.TextField(default='write about shop')),
            ],
            options={
                'db_table': 'ShopModel',
            },
        ),
    ]
